app/models.py
import os
from app import db
import jwt
from time import time
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(128))
    username = db.Column(db.String(128))
    password_hash = db.Column(db.String(128))

    def __repr__(self):
        return 'User {}'.format(self.username)

    def set_password(self, password, commit=False):
        self.password_hash = generate_password_hash(password)

        if commit:
            db.session.commit()

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def get_reset_token(self, expires=500):
        return jwt.encode({'reset_password': str(self.username), 'exp': time() + expires},
                           key=os.getenv('SECRET_KEY_FLASK'))

    @staticmethod
    def verify_reset_token(token):
        try:
            username = jwt.decode(token, key=os.getenv('SECRET_KEY_FLASK'))['reset_password']
            print(username)
        except Exception as e:
            print(e)
            return
        return User.query.filter_by(username=username).first()

    @staticmethod
    def create_user(username, password, email):

        user_exists = User.query.filter_by(username=username).first()
        if user_exists:
            return False

        user = User()

        user.username = username
        user.password = user.set_password(password)
        user.email = email

        db.session.add(user)
        db.session.commit()

        return True

    @staticmethod
    def login_user(username, password):

        user = User.query.filter_by(username=username).first()

        if user:
            if user.verify_password(password):
                return True

        return False

    @staticmethod
    def verify_email(email):

        user = User.query.filter_by(email=email).first()

        return user

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_jwt_extended import JWTManager
from flask_mail import Mail
import os

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
jwt = JWTManager()
mail = Mail()

def create_app(configuration):

    app = Flask(__name__)
    app.config.from_object(configuration)

    # Debug = True
    
    app.config["MAIL_SERVER"] = 'smtp.gmail.com'
    app.config["MAIL_PORT"] = 465
    app.config["MAIL_USE_SSL"] = True
    app.config["SQLALCHEMY_COMMIT_ON_TEARDOWN"] = True
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = True
    app.config["SQLALCHEMY_DATABASE_URI"] = "postgresql://gabriel:1234@localhost:5432/simpleteste"
    app.config["MAIL_USERNAME"] = os.getenv('MAIL_USERNAME')
    app.config["MAIL_PASSWORD"] = os.getenv('MAIL_PASSWORD')
    app.config["SECRET_KEY"] = 'secretkey'

    from app.views import app_routes
    app.register_blueprint(app_routes)

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    jwt.init_app(app)
    mail.init_app(app)

    return app

app/views.py
from app import db, mail
from app.email import send_email
from flask import request, redirect, url_for, render_template, Blueprint
from flask_jwt_extended import jwt_required, create_access_token, get_jwt_identity
from app.models import User
import flask_login

app_routes = Blueprint('app_routes', __name__)

@app_routes.route('/login', methods=['GET', 'POST'])
def login():

    if request.method == 'GET':
        return render_template('login.html'), 200

    if request.method == 'POST':

        username = request.form.get('username')
        password = request.form.get('password')

        if username and password:
            print(request.values)
            if User.login_user(username, password):
                return redirect(url_for('app_routes.home_page')), 200

        return render_template('login.html'), 400

    return render_template('login.html'), 400

@app_routes.route('/register', methods=['GET', 'POST'])
def register():

    if request.method == 'GET':
        return render_template('register.html'), 200

    if request.method == 'POST':

        username = request.form.get('username')
        password = request.form.get('password')
        email = request.form.get('email')

        if username and password and email:
            user_created = User.create_user(username, password, email)

            if user_created:
                return redirect(url_for('app_routes.login'))
            else:
                return render_template('register.html'), 400

        return render_template('register.html'), 400

@app_routes.route('/password_reset', methods=['GET', 'POST'])
def reset():

    if request.method == 'GET':
        return render_template('reset.html')

    if request.method == 'POST':

        email = request.form.get('email')
        user = User.verify_email(email)

        if user:
            send_email(user)

        return redirect(url_for('app_routes.login'))

@app_routes.route('/password_reset_verified/<token>', methods=['GET', 'POST'])
def reset_verified(token):

    user = User.verify_reset_token(token)
    if not user:
        print('no user found')
        return redirect(url_for('app_routes.login'))

    password = request.form.get('password')
    if password:
        user.set_password(password, commit=True)

        return redirect(url_for('app_routes.login'))

    return render_template('reset_verified.html')



@flask_login.login_required
@app_routes.route('/home', methods=['GET'])
def home_page():
    return render_template('home.html'), 200

app/templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %} - Flask Password Reset</title>
<nav>
  <h1>Flask Password Reset</h1>
  <ul>
    {% if g.user %}
      <li><span>{{ g.user['username'] }}</span>
      <li><a href="{{ url_for('app_routes.logout') }}">Log Out</a>
    {% else %}
      <li><a href="{{ url_for('app_routes.register') }}">Register</a>
      <li><a href="{{ url_for('app_routes.login') }}">Log In</a>
      <li><a href="{{ url_for('app_routes.reset')}}"> Reset Password </a>
      <li><a href="{{ url_for('app_routes.home_page') }}"> Home</a>
    {% endif %}
  </ul>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% block content %}{% endblock %}
</section>

app/templates/home.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Welcome Home!{% endblock %}</h1>
{% endblock %}

{% block content %}
  
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Log In{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="username">Username</label>
    <input name="username" id="username" required>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" required>
    <input type="submit" value="Log In">
  </form>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Register{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="email">Email</label>
    <input name="email" id="email" required>
    <label for="username">Username</label>
    <input name="username" id="username" required>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" required>
    <input type="submit" value="Register">
  </form>
{% endblock %}

app/templates/reset.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Reset Password{% endblock %}</h1>
{% endblock %}

{% block content %}
  <p>
    Please enter the email that you registered with.
    You will be sent an email that will allow you to reset your password.
  </p>

  <form method="post">
    <label for="email">Email</label>
    <input type="email" name="email" id="email" required>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

app/templates/reset_email.html
<p>
    To reset your password
    <a href="{{ url_for('app_routes.reset_verified', user=user, token=token, _external=True) }}">
        click here
    </a>.
</p>

app/templates/reset_verified.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Reset Password{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="password">Password</label>
    <input type="password" name="password" id="password" required>
    <input type="submit" value="Reset Password">
  </form>
{% endblock %}